"""
CareFlow AI — Module Dependency Diagram
Generated by IaC Planner agent | 2026-05-19

Shows deployment dependency order for 13 Bicep modules across 5 phases.
"""
from diagrams import Diagram, Cluster, Edge
from diagrams.azure.network import VirtualNetworks, DNSZones, FrontDoors, Firewall
from diagrams.azure.security import KeyVaults
from diagrams.azure.storage import StorageAccounts
from diagrams.azure.analytics import LogAnalyticsWorkspaces, EventHubs
from diagrams.azure.database import CosmosDb
from diagrams.azure.ml import CognitiveServices
from diagrams.azure.compute import ContainerRegistries
from diagrams.azure.web import AppServices
from diagrams.azure.integration import ServiceBus, DataFactories, APIManagement
from diagrams.azure.general import Resourcegroups

graph_attr = {
    "fontsize": "14",
    "bgcolor": "#F8F9FA",
    "pad": "0.5",
    "rankdir": "TB",
}

with Diagram(
    "CareFlow AI - Deployment Dependencies",
    filename="/workspaces/roda-infraops-hack/agent-output/careflow-ai/04-dependency-diagram",
    show=False,
    direction="TB",
    graph_attr=graph_attr,
    outformat="png",
):
    # Phase 1: Foundation
    with Cluster("Phase 1: Foundation", graph_attr={"style": "dashed", "color": "#0078D4"}):
        vnet = VirtualNetworks("networking.bicep\nVNet + 5 Subnets")
        dns = DNSZones("dns-zones.bicep\n6 Private DNS Zones")
        monitoring = LogAnalyticsWorkspaces("monitoring.bicep\nLog Analytics\n(PerGB2018)")

    # Phase 2: Security
    with Cluster("Phase 2: Security", graph_attr={"style": "dashed", "color": "#C00000"}):
        kv = KeyVaults("security.bicep\nKey Vault Premium")
        storage = StorageAccounts("storage.bicep\nStorage ZRS")

    # Phase 3: Data & AI
    with Cluster("Phase 3: Data & Messaging", graph_attr={"style": "dashed", "color": "#107C10"}):
        eh = EventHubs("messaging.bicep\nEvent Hubs + Service Bus")
        cosmos = CosmosDb("data.bicep\nCosmos DB\nAutoscale")
        ai = CognitiveServices("ai.bicep\nAzure OpenAI\n(Standard PAYG)")

    # Phase 4: Compute
    with Cluster("Phase 4: Compute", graph_attr={"style": "dashed", "color": "#FF8C00"}):
        acr = ContainerRegistries("container-registry.bicep\nACR Premium")
        compute = AppServices("compute.bicep\nContainer Apps\n(Agents + Proxy)")
        adf = DataFactories("data-factory.bicep\nData Factory V2")

    # Phase 5: Edge
    with Cluster("Phase 5: Edge & Governance", graph_attr={"style": "dashed", "color": "#5C2D91"}):
        apim = APIManagement("api.bicep\nAPIM + Front Door\n+ WAF")
        budget = Resourcegroups("budget.bicep\nConsumption Budget")

    # Dependencies (edges)
    # Foundation internal
    vnet >> Edge(style="bold") >> dns

    # Phase 2 depends on Phase 1
    vnet >> Edge(color="#C00000") >> kv
    dns >> Edge(color="#C00000") >> kv
    vnet >> Edge(color="#C00000") >> storage
    dns >> Edge(color="#C00000") >> storage

    # Phase 3 depends on Phase 1 & 2
    vnet >> Edge(color="#107C10") >> eh
    vnet >> Edge(color="#107C10") >> cosmos
    kv >> Edge(color="#107C10") >> cosmos
    vnet >> Edge(color="#107C10") >> ai
    kv >> Edge(color="#107C10") >> ai
    storage >> Edge(color="#107C10") >> ai  # AI Foundry needs storage

    # Phase 4 depends on Phase 1, 2, 3
    vnet >> Edge(color="#FF8C00") >> acr
    monitoring >> Edge(color="#FF8C00") >> compute
    acr >> Edge(color="#FF8C00") >> compute
    cosmos >> Edge(color="#FF8C00") >> compute
    ai >> Edge(color="#FF8C00") >> compute
    eh >> Edge(color="#FF8C00") >> compute
    storage >> Edge(color="#FF8C00") >> adf
    cosmos >> Edge(color="#FF8C00") >> adf

    # Phase 5 depends on Phase 4
    compute >> Edge(color="#5C2D91") >> apim
    kv >> Edge(color="#5C2D91") >> apim
