"""
CareFlow AI — Runtime Flow Diagram
Generated by IaC Planner agent | 2026-05-19

Shows request/auth/secret/event/telemetry paths at runtime.
"""
from diagrams import Diagram, Cluster, Edge
from diagrams.azure.network import FrontDoors
from diagrams.azure.integration import APIManagement, ServiceBus
from diagrams.azure.web import AppServices
from diagrams.azure.analytics import EventHubs, LogAnalyticsWorkspaces
from diagrams.azure.ml import CognitiveServices
from diagrams.azure.database import CosmosDb
from diagrams.azure.security import KeyVaults
from diagrams.azure.storage import StorageAccounts
from diagrams.azure.compute import ContainerRegistries
from diagrams.onprem.client import Users

graph_attr = {
    "fontsize": "14",
    "bgcolor": "#F8F9FA",
    "pad": "0.5",
    "rankdir": "LR",
}

edge_attr_request = {"color": "#0078D4", "style": "bold"}
edge_attr_event = {"color": "#107C10", "style": "dashed"}
edge_attr_secret = {"color": "#C00000", "style": "dotted"}
edge_attr_telemetry = {"color": "#FF8C00", "style": "dotted"}

with Diagram(
    "CareFlow AI - Runtime Flow",
    filename="/workspaces/roda-infraops-hack/agent-output/careflow-ai/04-runtime-diagram",
    show=False,
    direction="LR",
    graph_attr=graph_attr,
    outformat="png",
):
    # External
    hospitals = Users("25 Hospitals\n(EHR/Scheduling)")

    # Edge layer
    with Cluster("Edge Layer"):
        fd = FrontDoors("Front Door\n+ WAF (Detection)")
        apim = APIManagement("APIM\nStandard v2")

    # Ingestion
    with Cluster("Ingestion"):
        proxy = AppServices("Ingestion Proxy\n(PHI Validation)")
        eh = EventHubs("Event Hubs\n(Anonymized)")

    # Compute
    with Cluster("AI Agent Runtime"):
        agents = AppServices("Container Apps\n4 Agent Types")
        openai = CognitiveServices("Azure OpenAI\nGPT-4o / 4o-mini\n(Standard PAYG)")

    # Data
    with Cluster("Data Layer"):
        cosmos = CosmosDb("Cosmos DB\nAutoscale\n(hospital_id)")
        storage = StorageAccounts("Storage ZRS\nData Lake")

    # Security
    with Cluster("Security"):
        kv = KeyVaults("Key Vault\nPremium")

    # Observability
    with Cluster("Observability"):
        logs = LogAnalyticsWorkspaces("Log Analytics\n(PerGB2018)\n365-day retention")

    # Request path (blue, bold)
    hospitals >> Edge(**edge_attr_request, label="HTTPS") >> fd
    fd >> Edge(**edge_attr_request) >> apim
    apim >> Edge(**edge_attr_request, label="REST API") >> agents
    agents >> Edge(**edge_attr_request, label="Inference") >> openai

    # Event path (green, dashed)
    hospitals >> Edge(**edge_attr_event, label="Events") >> proxy
    proxy >> Edge(**edge_attr_event, label="Validated") >> eh
    eh >> Edge(**edge_attr_event) >> agents

    # Data path
    agents >> Edge(color="#107C10", label="Read/Write") >> cosmos
    eh >> Edge(color="#107C10") >> storage

    # Secret path (red, dotted)
    kv >> Edge(**edge_attr_secret, label="Secrets") >> agents
    kv >> Edge(**edge_attr_secret) >> apim
    kv >> Edge(**edge_attr_secret) >> proxy

    # Telemetry path (orange, dotted)
    agents >> Edge(**edge_attr_telemetry, label="Telemetry") >> logs
    proxy >> Edge(**edge_attr_telemetry) >> logs
    apim >> Edge(**edge_attr_telemetry) >> logs
